name: CD

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2

      - name: Update Assembly Version
        run: |
          python .github/workflows/update_assembly_version.py

      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release /nowarn:CS0472
          
      - name: Run Unit Tests
        working-directory: src/PollinationSDK.Tests
        run: |
          $Env:PollinationApiKey = "${{secrets.POLLINATION_STAGING_APIKEY}}"
          dotnet test --configuration Release

      - name: Deploy
        working-directory: src/PollinationSDK
        run: |
          dotnet pack --configuration Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet nuget push bin\Release\PollinationSDK.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
